"""create_media_&_audit_table

Revision ID: 153057a3f268
Revises: 9948e7cb84c9
Create Date: 2026-07-24 19:17:05.617945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153057a3f268'
down_revision: Union[str, Sequence[str], None] = '9948e7cb84c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expiries_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '24 hours'"), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key')
    )
    op.create_table('media_audit',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['medias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'viewer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_audit')
    op.drop_table('medias')
    # ### end Alembic commands ###
