"""Update_Media_table_to_hold_media_uploading

Revision ID: 15f143c595d4
Revises: 153057a3f268
Create Date: 2026-07-25 13:41:52.567993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f143c595d4'
down_revision: Union[str, Sequence[str], None] = '153057a3f268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('status', sa.String(), server_default='UPLOADING', nullable=False))
    op.alter_column('medias', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_column('medias', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('medias', 'file_size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('medias', 'status')
    # ### end Alembic commands ###
