"""updated log table

Revision ID: b19c7e220173
Revises: 15f143c595d4
Create Date: 2026-08-05 17:32:21.414427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19c7e220173'
down_revision: Union[str, Sequence[str], None] = '15f143c595d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_audit', sa.Column('media_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('media_audit_image_id_fkey'), 'media_audit', type_='foreignkey')
    op.create_foreign_key(None, 'media_audit', 'medias', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_column('media_audit', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_audit', sa.Column('image_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media_audit', type_='foreignkey')
    op.create_foreign_key(op.f('media_audit_image_id_fkey'), 'media_audit', 'medias', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('media_audit', 'media_id')
    # ### end Alembic commands ###
